# Generated by Django 5.2.4 on 2025-08-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=10)),
                ('crowd_level', models.CharField(choices=[('quiet', 'Quiet'), ('not_busy', 'Not Busy'), ('busy', 'Busy'), ('very_busy', 'Very Busy')], max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
