# Generated by Django 5.2.4 on 2025-08-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_report_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='crowd_level',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location_id',
        ),
        migrations.AddField(
            model_name='report',
            name='crowd_Level',
            field=models.CharField(default='not_specified', max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='location_Id',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
