# Generated by Django 5.2.4 on 2025-08-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_report_crowd_level_remove_report_location_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='crowd_Level',
            field=models.CharField(choices=[('quiet', 'Quiet'), ('not_busy', 'Not Busy'), ('busy', 'Busy'), ('very_busy', 'Very Busy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='location_Id',
            field=models.CharField(max_length=10),
        ),
    ]
