# Generated by Django 5.2.4 on 2025-08-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_report_crowd_level_alter_report_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='scrapeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_Id', models.CharField(max_length=10)),
                ('occupancy', models.IntegerField()),
                ('data', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='report',
            name='crowd_Level',
            field=models.CharField(max_length=20),
        ),
    ]
