# Generated by Django 5.2.4 on 2025-08-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_scrapedata_remove_report_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_Id', models.CharField(max_length=10)),
                ('occupancy', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Id', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='scrapedata',
            name='data',
        ),
    ]
